'use strict';
const test=require('node:test'),assert=require('node:assert/strict'),fs=require('node:fs'),vm=require('node:vm');
const source=fs.readFileSync(require.resolve('../src/core/dev-checkout'),'utf8');
function checkout(slot={ok:true}){const mod={exports:{}};const geo={addressLine:()=> 'verified address',lookupOnce:async()=>null,locate:async c=>c.lat===40&&c.lng===-74?{lat:40,lng:-74}:null};const booking={normaliseTime:t=>t,dateProblem:()=>null,timeProblem:()=>null,checkSlot:async()=>slot};const modules={'./pickup-timing':require('../src/core/pickup-timing'),'../db':{},'../config':{config:{supabase:{isDevelopment:true},shipday:{}}},'./pricing-economics':{},'./dynamic-order-pricing':{quoteCandidates:()=>({expiresAt:'2099-01-01'})},'./shipday-dispatch':{dispatchInstant:()=> '2099-01-01T15:00:00Z'},'../providers/couriers/shipday':{createClient:()=>({})},'./in-house-quote':{},'./public-courier-availability':{},'./booking':booking,'./partners':{list:async()=>[],hoursForAll:async()=>new Map(),loadByPartner:async()=>new Map(),plannedByPartner:async()=>new Map()},'./geocode':geo,'./booking-intents':{firstDateFor:f=>f.pickup_date},'./weight-based-pricing':{METHOD:'WEIGHT'}};vm.runInNewContext(source,{module:mod,require:id=>{assert.ok(id in modules,'unexpected dependency '+id);return modules[id];},console,Date});return mod.exports.previewQuote;}
const customer={id:'qa',lat:40,lng:-74,address_line1:'Verified Street',city:'Town',postal_code:'07001'};
const form={pickup_date:'2099-01-01',pickup_time:'10:00',plan:'ONE_TIME'};
test('scheduled checkout uses stored verified coordinates when a fresh free lookup is unavailable',async()=>{const result=await checkout()(customer,form,{policyOverride:{referenceWeightLb:30}});assert.equal(result.pickup_date,'2099-01-01');assert.equal(result.address.address_line1,'Verified Street');});
test('a duplicate pickup refusal explains what the customer can do',async()=>{await assert.rejects(checkout({ok:false,reason:'already_booked'})(customer,form,{policyOverride:{}}),/already have a pickup booked.*Move it/i);});

