'use strict';
const test=require('node:test'),assert=require('node:assert/strict');
const {createService}=require('../src/core/partner-intake');
function board(live){const records={orders:[{id:'o',order_number:9025,status:'REQUESTED',partner_id:'s'}],partner_order_intakes:[],shipday_dispatch_plans:[{order_id:'o',leg:'TO_PARTNER',state:'COMPLETED'}],courier_deliveries:[],laundromat_workflow_settings:{weight_tolerance_lb:1}};const db={from(table){const q={select(){return q;},or(){return q;},in(){return q;},order(){return q;},eq(){return q;},maybeSingle(){return q;},then(resolve){return Promise.resolve({data:records[table]}).then(resolve);}};return q;}};return createService({db,deliveryInfo:async()=>live});}
test('verified collected intake stays visible after Shipday removes carrier',async()=>{
 const rows=await board({ok:true,assignmentVerified:false,provider_status:'ALREADY_DELIVERED'}).list('s');assert.equal(rows.length,1);assert.equal(rows[0].canAccept,true);assert.equal(rows[0].driver,null);
});
test('unverified carrierless deliveries remain hidden',async()=>{assert.equal((await board({ok:false,assignmentVerified:false}).list('s')).length,0);});
function completion(){let create;try{create=require('../src/core/delivery-completion').createCompletion;}catch{create=()=>({reconcile:async()=>({skipped:true})});}const now=Date.now(),order={id:'o',order_number:9025,dev_quote_id:'q',status:'OUT_FOR_DELIVERY',payment_status:'PAID',customers:{},partner_id:'s'},plan={id:'p',order_id:'o',leg:'TO_CUSTOMER',mode:'IN_HOUSE',driver_id:'7',version:4,external_reference:'LYNDRY-DEV-9025-RETURN',shipday_order_id:'123',simulation:false,state:'REVIEW'};let proofs=0,commits=0;const seen={terminal:true,rank:3,remoteId:'123',observedAt:new Date(now).toISOString(),deliveryPhotos:['proof']};const service=create({now:()=>now,load:async()=>({order,plan,shop:{id:'s'}}),observe:async()=>seen,savePhoto:async()=>{proofs++;return 'o/recovery-verified.jpg';},complete:async args=>{commits++;assert.equal(args.plan.id,'p');const already=order.status==='DELIVERED';order.status='DELIVERED';plan.state='COMPLETED';return {ok:true,already};}});return {service,order,plan,seen,counts:()=>({proofs,commits})};}
test('verified paid return automatically completes original REVIEW plan and replays harmlessly',async()=>{
 const f=completion();assert.equal((await f.service.reconcile(9025)).ok,true);await f.service.reconcile(9025);assert.equal(f.order.status,'DELIVERED');assert.equal(f.plan.state,'COMPLETED');assert.deepEqual(f.counts(),{proofs:1,commits:1});
});
for(const change of [f=>f.order.payment_status='FAILED',f=>f.order.status='READY',f=>f.plan.simulation=true,f=>f.plan.mode='THIRD_PARTY',f=>f.seen.deliveryPhotos=[],f=>f.seen.remoteId='999',f=>f.seen.observedAt='1970-01-01',f=>f.seen.terminal=false])test('invalid completion evidence never saves proof or completes '+change.toString(),async()=>{const f=completion();change(f);await f.service.reconcile(9025);assert.deepEqual(f.counts(),{proofs:0,commits:0});});
test('notification suppression does not block operational completion; already manually delivered stays untouched',async()=>{
 const f=completion();f.order.delivery_notifications_suppressed=true;await f.service.reconcile(9025);assert.equal(f.order.status,'DELIVERED');
 const manual=completion();manual.order.status='DELIVERED';manual.order.delivery_notifications_suppressed=true;await manual.service.reconcile(9025);assert.deepEqual(manual.counts(),{proofs:0,commits:0});
});
test('completed orders render terminal detail sync without false editing failure or retry button',()=>{
 const {syncStatus}=require('../src/web/order-overview');const html=syncStatus({status:'DELIVERED',order_number:9025},[{leg:'TO_CUSTOMER',state:'REVIEW',problem:'This order is closed. Review manually.'}]);assert.match(html,/Closed/);assert.doesNotMatch(html,/Needs attention|Review manually|sync-shipday/);
});
test('billable weight uses authoritative recorded dynamic measured weight without repricing or inventing a legacy weight',()=>{
 const {orderOverview}=require('../src/web/order-overview');const render=order=>orderOverview({order,customer:{}});
 assert.match(render({dev_quote_id:'q',pricing_snapshot:{},weight_lb:30,partner_weight_lb:30,price_cents:5916,payment_status:'PAID'}),/<dt>Billable weight<\/dt><dd>30 lb/);
 assert.match(render({weight_lb:30,payment_status:'PAID'}),/<dt>Billable weight<\/dt><dd>Not finalized/);
});
test('completion observation is independent from message suppression but same wrong driver still rejects',async()=>{
 const {observe}=require('../src/core/delivery-sms');const order={order_number:9025,status:'OUT_FOR_DELIVERY',delivery_notifications_suppressed:true,payment_status:'PAID',customers:{address_line1:'Home'}};const shop={address_line1:'Shop'};const plan={leg:'TO_CUSTOMER',mode:'IN_HOUSE',driver_id:'7',shipday_order_id:'123',external_reference:'LYNDRY-DEV-9025-RETURN'};const remote={orderId:123,orderNumber:plan.external_reference,restaurant:{address:'Shop'},customer:{address:'Home'},orderStatus:{orderState:'ALREADY_DELIVERED'},assignedCarrier:{id:7}};const f={order,shop,plan,provider:{findOrders:async()=>[remote]},tracking:async()=>null};assert.equal(await observe(f),null);assert.equal((await observe({...f,forCompletion:true}))?.terminal,true);remote.assignedCarrier.id=8;assert.equal(await observe({...f,forCompletion:true}),null);
});

test('historical non recovery proof does not block verified terminal plan repair',async()=>{const f=completion();f.order.status='DELIVERED';f.order.delivery_photo_path='o/old-photo.jpg';await f.service.reconcile(9025);assert.equal(f.plan.state,'COMPLETED');assert.equal(f.counts().proofs,1);assert.equal(f.order.delivery_photo_path,'o/old-photo.jpg');});
for(const field of ['thirdPartyAssignedAnytime','thirdPartyTrackingLink','dOrderState'])test('in house completion refuses '+field+' even with matching stale driver',async()=>{const {observe}=require('../src/core/delivery-sms');const plan={leg:'TO_CUSTOMER',mode:'IN_HOUSE',driver_id:'7',shipday_order_id:'123',external_reference:'LYNDRY-DEV-9025-RETURN'};const remote={orderId:123,orderNumber:plan.external_reference,restaurant:{address:'Shop'},customer:{address:'Home'},orderStatus:{orderState:'ALREADY_DELIVERED'},assignedCarrier:{id:7},[field]:true};const seen=await observe({order:{status:'OUT_FOR_DELIVERY',customers:{address_line1:'Home'}},shop:{address_line1:'Shop'},plan,provider:{findOrders:async()=>[remote],status:async()=>({status:'delivered',courier:{name:'Courier'}})},tracking:async()=>null,forCompletion:true});assert.equal(seen,null);});
test('committed migration chain preserves silent manual recovery and no photo UI',async()=>{const fs=require('node:fs');let migration='';try{migration=fs.readFileSync(require('node:path').join(__dirname,'../supabase/migrations/0140_manual_delivery_without_photo.sql'),'utf8');}catch{}assert.match(migration,/delivery_notifications_suppressed.*p_source='MANUAL'/);const {createRecovery}=require('../src/core/order-recovery');let saved=0,completed;const recover=createRecovery({load:async()=>({order:{status:'OUT_FOR_DELIVERY',payment_status:'PAID'},plan:null}),savePhoto:async()=>{saved++;},complete:async x=>{completed=x;return {ok:true};}});await recover(1,'deliver',{reason:'Confirmed QA delivery',confirmed:'yes'},{id:'admin'});assert.equal(saved,0);assert.equal(completed.source,'MANUAL');assert.equal(completed.path,null);const html=require('../src/web/order-header-actions').render({order:{dev_quote_id:'q',status:'OUT_FOR_DELIVERY'},can:{override:true}});assert.doesNotMatch(html,/name="photo"/);});
