'use strict';
const test=require('node:test'),assert=require('node:assert/strict'),fs=require('node:fs'),vm=require('node:vm');const source=fs.readFileSync(require.resolve('../src/routes/admin'),'utf8');const code=source.slice(source.indexOf("router.post('/ops/customers/:id/order'"),source.indexOf("router.get('/ops/customers/:id',"));
async function request(form,hasCard=true,category='ONE_TIME',customerCategory=null){let handler,booked=null,html='',redirect='';const customer={id:'11111111-1111-1111-1111-111111111111',default_payment_method_id:hasCard?'pm_test':null,pricing_category:customerCategory};const quote={id:'quote-1',snapshot:{category},pickup_date:'2099-01-01',pickup_time:'10:00'};const checkout={enabled:true,createQuote:async()=>quote,read:async()=>quote,approve:async()=>quote};const res={type(){return this;},status(){return this;},send(s){html=s;return this;},redirect(_status,url){redirect=url;return this;}};vm.runInNewContext(code,{router:{post:(_p,...f)=>{handler=f.at(-1);}},guard:()=>{},may:()=>()=>{},UUID:/^[a-f0-9-]{36}$/,db:{from:()=>({select(){return this;},eq(){return this;},maybeSingle:async()=>({data:customer})})},adminPage:x=>x.body,phoneOrderForm:x=>x.problem||'form',booking:{DOORS:{PHONE:'PHONE'},bookPickup:async(_c,o)=>{booked=o;return{ok:true,order:{order_number:99}};}},require:id=>id.includes('dev-checkout')?checkout:id.includes('booking-price')?{review:(_q,fields)=>'<form action="/account/book">Review your pickup.'+fields+'</form>'}:require(id),escapeHtml:String,encodeURIComponent,notFoundPage:()=>{},console});await handler({params:{id:customer.id},body:{pickup_date:'2099-01-01',pickup_time:'10:00',silent:'yes',...form},opsUser:{id:'staff'},protocol:'http',get:n=>n==='origin'?'http://pos.localhost:3000':'pos.localhost:3000'},res,e=>{throw e;});return{booked,html,redirect};}
test('POS shows the current saved price before creating an order',async()=>{const r=await request({});assert.equal(r.booked,null);assert.match(r.html,/Review your pickup/);assert.match(r.html,/action="\/ops\/customers\//);assert.match(r.html,/name="silent" value="yes"/);});
test('POS passes its approved quote to the shared booking service',async()=>{const r=await request({dev_quote_id:'quote-1',price_consent:'yes'});assert.equal(r.booked.devQuoteId,'quote-1');assert.equal(r.booked.placedVia,'PHONE');assert.match(r.redirect,/orders\/99/);});
test('no-card price review never creates a real pickup',async()=>{const r=await request({dev_quote_id:'quote-1',price_consent:'yes'},false);assert.equal(r.booked,null);assert.match(r.html,/card.*before.*book|no pickup.*booked/i);});

test('POS rejects a subscription quote supplied for a one-time order',async()=>{const r=await request({dev_quote_id:'quote-1',price_consent:'yes'},true,'SUBSCRIPTION');assert.equal(r.booked,null);assert.match(r.html,/one-time quote/i);});
test('POS preserves an agreed wholesale quote',async()=>{const r=await request({dev_quote_id:'quote-1',price_consent:'yes'},true,'WHOLESALE','WHOLESALE');assert.equal(r.booked.devQuoteId,'quote-1');});

function orderForm(development){const fn=source.slice(source.indexOf('function phoneOrderForm('),source.indexOf("router.get('/ops/customers/:id/order'"));return vm.runInNewContext(fn+';phoneOrderForm({customer:{name:"QA",preferences:{}}})',{escapeHtml:String,formatPhone:String,phoneBanner:String,wash:{describeSaved:()=>''},booking:{hasPreferences:()=>true,listWindows:()=> 'morning'},require:()=>({enabled:development})});}
test('required development time is described as an exact pickup time',()=>{const html=orderForm(true);assert.match(html,/Choose an exact pickup time/i);assert.doesNotMatch(html,/Optional\. They get the window/);});
test('production keeps optional pickup window wording',()=>{assert.match(orderForm(false),/Optional\. They get the window/);});
