'use strict';
const test=require('node:test');const assert=require('node:assert/strict');
const {createDispatcher,dispatchInstant}=require('../src/core/shipday-dispatch');
function fixture(patch={},options={}){
 let row={id:'plan',order_id:'order',leg:'TO_PARTNER',dispatch_at:'2026-09-27T10:00:00Z',state:'PLANNED',mode:'THIRD_PARTY',version:0,history:[],...patch};
 const calls=[];let checks=0;
 const store={get:async()=>structuredClone(row),claim:async old=>{if(old.version!==row.version||old.state!==row.state)return null;row={...row,state:'PROCESSING',version:row.version+1};return structuredClone(row);},save:async(old,change,event)=>{if(old.version!==row.version)throw Error('conflict');row={...row,...change,version:row.version+1,history:[...row.history,event]};return structuredClone(row);}};
 const provider={drivers:async()=>[{id:'driver',isActive:true,isOnShift:!options.offline}],createOrder:async()=>{calls.push('create');return{id:'external'};},assign:async()=>{calls.push('third-party');if(options.timeout)throw Error('timeout');return options.refused?{ok:false,reason:'Over approved budget'}:{ok:true,service:'Courier'};},assignDriver:async()=>{calls.push('in-house');return{ok:true,courier:{name:'House driver'}};},status:async()=>({status:options.collected?'PICKED_UP':'ASSIGNED'}),cancel:async()=>{calls.push('cancel');return{ok:!options.cancelUncertain};},unassign:async()=>{calls.push('release');return{ok:true};}};
 const validate=async()=>{checks++;return options.block || (options.changed&&checks>1)?{ok:false,reason:'Card or order eligibility check failed'}:{ok:true,trip:{},budgetCents:999};};
 return{...createDispatcher({store,provider,validate,now:()=>Date.parse('2026-09-27T12:00:00Z')}),row:()=>row,calls};
}
test('one automatic third-party request despite concurrent ticks and subsequent retries',async()=>{const f=fixture();await Promise.all([f.run('plan'),f.run('plan')]);await f.run('plan');assert.deepEqual(f.calls,['create','third-party']);assert.equal(f.row().state,'ASSIGNED');});
test('future dispatch does not call vendor; an in-house choice is saved for its due time',async()=>{const f=fixture({dispatch_at:'2026-09-28T12:00:00Z'});await f.run('plan');assert.deepEqual(f.calls,[]);assert.equal((await f.run('plan',{mode:'IN_HOUSE',driverId:'driver'},'staff:one')).planned,true);assert.equal(f.row().mode,'IN_HOUSE');assert.deepEqual(f.calls,[]);assert.equal(f.row().history.at(-1).actor,'staff:one');});
test('in-house override checks availability and assigns selected driver',async()=>{const f=fixture();assert.equal((await f.run('plan',{mode:'IN_HOUSE',driverId:'driver'})).ok,true);assert.deepEqual(f.calls,['create','in-house']);const offline=fixture({}, {offline:true});await offline.run('plan',{mode:'IN_HOUSE',driverId:'driver'});assert.deepEqual(offline.calls,[]);});
test('card or order eligibility refusal stops vendor writes and is rechecked before assignment',async()=>{const f=fixture({}, {block:true});await f.run('plan');assert.deepEqual(f.calls,[]);const changed=fixture({}, {changed:true});await changed.run('plan');assert.deepEqual(changed.calls,['create']);assert.equal(changed.row().state,'BLOCKED');});
test('confirmed cancellation precedes the in-house replacement',async()=>{const f=fixture({state:'ASSIGNED',shipday_order_id:'external'});await f.run('plan',{mode:'IN_HOUSE',driverId:'driver',acceptCancellationFee:true});assert.deepEqual(f.calls,['cancel','in-house']);assert.equal(f.row().state,'ASSIGNED');});
test('cancellation needs acknowledgment; ambiguous cancellation never dispatches a second driver',async()=>{const f=fixture({state:'ASSIGNED',shipday_order_id:'external'});await f.run('plan',{mode:'IN_HOUSE',driverId:'driver'});assert.deepEqual(f.calls,[]);const uncertain=fixture({state:'ASSIGNED',shipday_order_id:'external'},{cancelUncertain:true});await uncertain.run('plan',{mode:'IN_HOUSE',driverId:'driver',acceptCancellationFee:true});await uncertain.run('plan');assert.deepEqual(uncertain.calls,['cancel']);assert.equal(uncertain.row().state,'REVIEW');});
test('collected laundry blocks reassignment and same-driver selection is idempotent',async()=>{const f=fixture({state:'ASSIGNED',shipday_order_id:'external'},{collected:true});await f.run('plan',{mode:'IN_HOUSE',driverId:'driver',acceptCancellationFee:true});assert.deepEqual(f.calls,[]);const same=fixture({state:'ASSIGNED',shipday_order_id:'external',mode:'IN_HOUSE',driver_id:'driver'});assert.equal((await same.run('plan',{mode:'IN_HOUSE',driverId:'driver'})).already,true);assert.deepEqual(same.calls,[]);});
test('assignment timeout pauses retries while explicit budget refusal blocks safely',async()=>{const f=fixture({}, {timeout:true});await f.run('plan');await f.run('plan');assert.deepEqual(f.calls,['create','third-party']);assert.equal(f.row().state,'REVIEW');const refused=fixture({}, {refused:true});await refused.run('plan');assert.equal(refused.row().state,'BLOCKED');});
test('Eastern dispatch times reject ambiguous, nonexistent and invalid wall clocks',()=>{assert.equal(dispatchInstant('2026-09-27','17:00'),'2026-09-27T21:00:00.000Z');assert.equal(dispatchInstant('2026-03-08','02:30'),null);assert.equal(dispatchInstant('2026-11-01','01:30'),null);assert.equal(dispatchInstant('2026-02-30','17:00'),null);assert.equal(dispatchInstant('2026-09-27','25:00'),null);});
